### ISSUE TITLE
Sender example file crash

### ISSUE THREAD

**Issue by antlas0** [markqvist/LXMF#21]
Hello,

Thank you for sharing this interesting project.

**Describe the Bug**
I encountered an error while playing with the examples files, in particular the `docs/example_sender.py` file.

**To Reproduce**
* Basic RNS configuration with shared instance on my system.
* Call `python docs/example_receiver.py` and `python docs/example_sender.py` in separate processes.
* Proceed with the indications appearing.

**Expected Behavior**
Seing a message received by the receiver process, and reading on stdout a similar output:
```bash
[2024-XX-YY HH:MM:SS] [Notice]  +--- LXMF Delivery ---------------------------------------------
[2024-XX-YY HH:MM:SS] [Notice]  | Source hash            : <47de73...>
[2024-XX-YY HH:MM:SS] [Notice]  | Source instance        : <lxmf.delivery.3cc32cdba2e07440e43dff98792d6f82/47de73...>
[2024-XX-YY HH:MM:SS] [Notice]  | Destination hash       : <deadbeef_abcdef>
[2024-XX-YY HH:MM:SS] [Notice]  | Destination instance   : <lxmf.delivery.07a5207f9a8d60560713056def4e6d38/d7ababfac764cefa597a13fe706f32b4>
[2024-XX-YY HH:MM:SS] [Notice]  | Transport Encryption   : Curve25519
[2024-XX-YY HH:MM:SS] [Notice]  | Timestamp              : 2024-XX-YY HH:MM:SS
[2024-XX-YY HH:MM:SS] [Notice]  | Title                  : 
[2024-XX-YY HH:MM:SS] [Notice]  | Content                : If wishes were horses then beggars might fly. Stuff like that. It's enough to drive you crazy.
[2024-XX-YY HH:MM:SS] [Notice]  | Fields                 : {12: [1730626978.8813243, b'\xcf_\xef\xde\xa7>\xe2\xde\xd1+\xa9\xba\xbb\xa3\x95\x0b']}
[2024-XX-YY HH:MM:SS] [Notice]  | Ratchet                : b'\n\xc1\xea\x1d~`\xdd\x0eJ\x13'
[2024-XX-YY HH:MM:SS] [Notice]  | Message signature      : Validated
[2024-XX-YY HH:MM:SS] [Notice]  | Stamp                  : Validated
[2024-XX-YY HH:MM:SS] [Notice]  +---------------------------------------------------------------
```

**Logs & Screenshots**
* Logs of the `doc/example_receiver.py` file execution:
```bash
python docs/example_receiver.py 
[2024-XX-YY 11:20:23] [Notice] Ready to receive on: <deadbeef_abcdef>

[2024-XX-YY 11:21:04] [Notice] Announcing lxmf.delivery destination...
```
* Logs of the `doc/example_sender.py` file execution:
```bash
python docs/example_sender.py 
[2024-XX-YY 11:20:58] [Notice] Source announced
Recipient:  deadbeef_abcdef
[2024-XX-YY 11:21:01] [Notice] Destination is not yet known. Requesting path and waiting for announce to arrive...
Exception in thread Thread-6 (process_deferred_stamps):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "reticulum/LXMF/LXMF/LXMRouter.py", line 1744, in process_deferred_stamps
    generated_stamp = selected_lxm.get_stamp()
  File "reticulum/LXMF/LXMF/LXMessage.py", line 325, in get_stamp
    generated_stamp, value = LXStamper.generate_stamp(self.message_id, self.stamp_cost)
  File "reticulum/LXMF/LXMF/LXStamper.py", line 57, in generate_stamp
    value = stamp_value(workblock, stamp)
  File "reticulum/LXMF/LXMF/LXStamper.py", line 30, in stamp_value
    i = int.from_bytes(material)
TypeError: from_bytes() missing required argument 'byteorder' (pos 2)
```

**System Information**
Here are my environment info:
```txt
Ubuntu 22.04
Python 3.10.12
rns 0.8.4
lxmf 0.5.6
```

**Additional context**
After an investigation and the backtrace, it turns out that the `LXStamper.stamp_value` raises an exception. It is due to the call to `int.from_bytes` that seems to not comply with the signature.
If it can be of any help, I managed to fix [1] this small issue after forking your repository. But if I well understood the perimeter of this bug, a small commit on your side should do the job. 

[1] Patch view: https://github.com/markqvist/LXMF/compare/master...antlas0:LXMF:fix/int_from_bytes

Thank you !

**Comment by markqvist** [comment]
Ah, good catch! There was not a default value for the `byteorder` argument before Python 3.11. From Python docs:

> Changed in version 3.11: Added default argument values for length and byteorder.

Thanks for reporting it, will issue fix shortly!
